### ISSUE TITLE
14屆資訊補充

### ISSUE THREAD

**Issue by adks3489** [WHCSC/whcsc.github.io#1]
Hi,
我是14屆的社長，我補充一些14屆的資訊。

社長：蔣朝勛《國立中山大學 資訊工程學系》
副社：劉建宏《國立陽明大學 生命科學系》
公關：林鳴奕《逢甲大學 電子工程學系》
公關：李政祐 
美工：林鍵智《中央警察大學》
總務：鍾佳樺《國立臺灣大學 經濟學系》
活動：林俊豪《國立台灣科技大學 企業管理學系》
教學：林存中《國立中山大學 機械與機電工程學系》

寒訓是九校十社(台中一中、台中二中、台中女中、文華高中、曉明女中、彰化高中、彰化女中、新竹高中、新竹女中)

**Comment by ncchen99** [comment]
十分感謝，不好意思現在才看到😓，謝謝龍騎學長 !
